
extern crate cc;


fn main() {
	println!("cargo:rustc-link-arg=-mfloat-abi=hard");
    cc::Build::new()
    .file("Core/Inc/stm32f4xx_hal_conf.h")
    .file("Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f4xx.h")
    .file("Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.h")
    .file("Core/Inc/gpio.h")
    .file("Core/Src/gpio.c")
    .file("Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c")
.file("Core/Src/system_stm32f4xx.c")
.file("Core/Src/crc32.c")
.file("Core/Src/sysmem.c")
.file("Core/Src/iwdg.c")
.file("Core/Src/func.c")
.file("Core/Src/stm32f4xx_it.c")
.file("Core/Src/main.c")
.file("Core/Src/trace.c")
.file("Core/Src/syscalls.c")
.file("Core/Src/stm32f4xx_hal_msp.c")
.file("Core/Inc/stm32f4xx_it.h")

.file("Core/Inc/main.h")

.file("Core/Inc/trace.h")
.file("Core/Inc/crc32.h")
.file("Core/Inc/iwdg.h")
.file("Core/Startup/startup_stm32f407vgtx.s")

.file("Drivers/CMSIS/Device/ST/STM32F4xx/Include/system_stm32f4xx.h")
.file("Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f407xx.h")
.file("Drivers/CMSIS/Include/core_cm1.h")
.file("Drivers/CMSIS/Include/cmsis_compiler.h")
.file("Drivers/CMSIS/Include/core_cm23.h")
.file("Drivers/CMSIS/Include/core_cm3.h")
.file("Drivers/CMSIS/Include/cmsis_armclang.h")
.file("Drivers/CMSIS/Include/core_sc000.h")
.file("Drivers/CMSIS/Include/core_armv8mml.h")
.file("Drivers/CMSIS/Include/core_sc300.h")
.file("Drivers/CMSIS/Include/mpu_armv8.h")
.file("Drivers/CMSIS/Include/mpu_armv7.h")
.file("Drivers/CMSIS/Include/core_cm33.h")
.file("Drivers/CMSIS/Include/cmsis_version.h")
.file("Drivers/CMSIS/Include/cmsis_armcc.h")
.file("Drivers/CMSIS/Include/tz_context.h")
.file("Drivers/CMSIS/Include/core_cm7.h")
.file("Drivers/CMSIS/Include/core_cm0.h")
.file("Drivers/CMSIS/Include/core_cm4.h")
.file("Drivers/CMSIS/Include/core_cm0plus.h")
.file("Drivers/CMSIS/Include/cmsis_gcc.h")
.file("Drivers/CMSIS/Include/cmsis_iccarm.h")
.file("Drivers/CMSIS/Include/core_armv8mbl.h")
.file("Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c")
.file("Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c")
.file("Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c")
.file("Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c")
.file("Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c")
.file("Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c")
.file("Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c")

.file("Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c")
.file("Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c")
.file("Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c")
.file("Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c")
.file("Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c")
.file("Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c")
.file("Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.c")
.file("Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c")
.file("Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal.h")
.file("Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_flash_ramfunc.h")
.file("Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_iwdg.h")
.file("Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_flash_ex.h")
.file("Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_rcc.h")
.file("Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_dma.h")
.file("Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_tim.h")
.file("Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_rcc_ex.h")
.file("Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_dma_ex.h")
.file("Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_pwr.h")
.file("Drivers/STM32F4xx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h")
.file("Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_gpio.h")
.file("Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_tim_ex.h")
.file("Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_cortex.h")
.file("Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_exti.h")
.file("Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_pwr_ex.h")
.file("Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_def.h")
.file("Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_gpio_ex.h")
.file("Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_flash.h")
;
}
