[package]
name = "rust-to-c"
version = "0.1.0"
authors = ["Mike", "Leo", "Roman", "Sveta"]
build = "build.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1.0"

[lib]
name = "rust_main"
crate-type = ["staticlib"]
